name: acme_client
version: 1.3.1
homepage: https://github.com/Ephenodrom/Dart-Acme-Client
publish_to: https://onepub.dev/api/jbbxpsdavu/
description: ACME client which allows you to obtain a HTTPS Certificate from any ACME CA such as Lets Encrypt.
environment: 
  sdk: '>=2.12.0 <4.0.0'
dependencies: 
  basic_utils: ^5.5.4
  json_annotation: ^4.1.0
  dio: ^5.0.0
  jose:
    hosted:
      url: https://onepub.dev/api/jbbxpsdavu/
      name: jose
    version: ^0.3.5
dev_dependencies: 
  lints: ^3.0.0
  test: ^1.16.0
  build_runner: ^2.3.0
  json_serializable: ^6.6.1
